# Generated by Django 5.0.4 on 2024-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('content', models.TextField()),
                ('faculty', models.CharField(choices=[('ARCHITECT', 'Arxitektura va muxandislik fakulteti'), ('IT', 'Axborot texnologiyalari (IT) va iqtisodiyot fakulteti'), ('SVUT', 'Sanoat va umumtexnika fakulteti'), ('HUMANITY', 'Ijtimoiy gumanitar fanlar va tillar fakulteti')], max_length=10)),
                ('daytime', models.FloatField()),
                ('externally', models.FloatField()),
                ('type', models.CharField(choices=[('BA', 'Bakalavr'), ('MA', 'Magistratura')], max_length=2)),
            ],
        ),
    ]
