# Generated by Django 5.0.4 on 2024-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_new_alter_direction_daytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.CharField(choices=[('Arxitektura va muxandislik fakulteti', 'ARCHITECT'), ('Axborot texnologiyalari (IT) va iqtisodiyot fakulteti', 'IT'), ('Sanoat va umumtexnika fakulteti', 'SVUT'), ('Ijtimoiy gumanitar fanlar va tillar fakulteti', 'HUMANITY')], max_length=53),
        ),
    ]
